---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2 
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: papilloretna/node_image:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 3000
